language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
script:
- npm install
- npm run build
deploy:
  provider: heroku
  api_key:
    secure: Y40CLeBWV5stV5jzYmauA2hdo/zxpL+8RxVmXcJZd/sbB7DxGYsLnd7HOvtq4j7Gv5J58pihZv/6+SXz6Vprll1j43867ql+4PlGNxD9IbIeB0kemEhhTHbBpYsuntmhXhxSOR6rxddPv+2yPf+G1k6y06i6pOXOqeTM0Rq4O8LuyQbmz0v2rlZ4+JONrZTtLAlhJPxHdv732FjLcRaKlVZaXl0240jgVbrauc9vrUV+Y15F0oyhflU0xCE+pfhwofhgfQZI/LpphqPQLFArJf1x70cv3/2D5+6neEBksvDMedRUWUPrWrzmZ4oYGMuTYoZALWhLWamK+uDt8NDFFJ02/x5pNZ04EJi/SxvGrvGFvtQjSKNGmYnZCb9Du5UsIZYMaaHPfN/QKNEZdfXhMjypOY82wb0W+a4ezcPzBzLIv4MGWfBX9McIBY5QsXJVzFm4V0WD+qZLYAV+IokI/9V1BZzub4eON3O5bf5x8CeG2QAMu+dJnq+6lxn+jXXdbdaqMOwE1qkmf9WMonVsuiiMiS2tdMduuXfC6YK/jSG9l1QBJcv6lk0vRx627/s8xrSdOtjCTSqBoadZdtqh4R9yCBnPnmFWJWccMw3OleiXrMVpzAzwSS1L8RvZlOPgI/DUCgdIi66HUcSj55XGvVLp/1BKVd4nizEx/nxbefQ=
  app: shielded-coast-81308
  on: master-prod
