language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
script:
- npm install
- npm run build
deploy:
  provider: heroku
  api_key:
    secure: cjQ9Ub6rH+LwCTeIgXfNzaabbIV1pmwAG/DHuhRaG89FjW+cY0xqNz3eKTDBl+6r6dtLhhx0uw/nAK/flKJH0AcLn6a4slvxksH2T5YeSCFKW/ZR7aZp7pz0s5OfuUCKZzx64FR7o7MEtIdxCW/NJiD7SKDYNdOSf3RyoYz2UwA5HCasvIFKWwG1p6FnNP+3f21w/X/gkv5uoYOX95qwh6/m8aG3BEc/I/t1N4xoGLyLYZ5jzNhIMMGFfC38CIUMIXSHghgOYRtH52zveYXv2ibDSMFvQZTvY26LlY5RPCg6lD2kKgjdfkVl4nn6lkxfN+JmDvL/a+Z+FNi6dF2zIYbQAtjtH7uLAvYWxd35+ThYe6EUWbpy1q8ZFjrqiiQ14L/FPXN5sCScyb3uwbulgkMGsTywPzILtwTAabubyHDpf4t5NSZArYpGOd/JC/aaGBsaJIg6Z5BTh7ewQos8ilX43QQQe7BdWPpfxWR+M8RDpIGgcdYcdKEZlgryvatX83CpW7qQGUYzC1Q7BPLsLB8J19PEIqHKne9ONas3o0eR+i4r8IDC2J1Lk4m8XRONrwsV+5+cpuCbOVMJ8Zg0z3C5AFlfnmsKMrlWOnZKQSQLhblBgQ+8KhBQuAeb0BFIsrhbo6agWUD9H8dJbQyHzUerLc2jt4Hz0cxCXD75I2o=
  app: shielded-coast-81308
  on: master-prod
